# This workflow will install Python dependencies, run test_blockchain and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Bash Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Only on PR
      id: docker_build
      uses: docker/build-push-action@v3
      if: ${{ github.ref != 'refs/heads/main' }}
      with:
        push: true
        tags: marcelndeffo/tools:ops-scripts-${{ github.sha }}
    - name: Build Only on Main
      id: docker_build_push
      uses: docker/build-push-action@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        push: true
        tags: marcelndeffo/tools:ops-scripts

  test:
    needs: build
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: marcelndeffo/tools:ops-scripts-${{ github.sha }}
      env:
        VERBOSE: "TRUE"
    steps:
      - name: Run Test Suite
        id: test_docker
        run: |
          /src/tests/compute-audio-expensive.sh
          /src/tests/compute-audio.sh
          /src/tests/browse-github.sh
